// ============================================================
// AtlasOps AI — Export Utilities
// CSV export, executive summary generation
// ============================================================

// --- CSV Export ---

export function exportToCSV(
  data: Record<string, unknown>[],
  filename: string,
  columns?: { key: string; header: string }[]
): void {
  if (data.length === 0) return;

  const cols = columns || Object.keys(data[0]).map(k => ({ key: k, header: k }));
  const header = cols.map(c => `"${c.header}"`).join(",");
  const rows = data.map(row =>
    cols.map(c => {
      const val = row[c.key];
      if (typeof val === "string") return `"${val.replace(/"/g, '""')}"`;
      if (typeof val === "number") return String(val);
      return `"${String(val ?? "")}"`;
    }).join(",")
  );

  const csv = [header, ...rows].join("\n");
  downloadFile(csv, `${filename}.csv`, "text/csv;charset=utf-8;");
}

// --- JSON Export ---

export function exportToJSON(data: unknown, filename: string): void {
  const json = JSON.stringify(data, null, 2);
  downloadFile(json, `${filename}.json`, "application/json");
}

// --- Executive Summary Text ---

export function generateExecutiveSummaryText(metrics: {
  totalRevenue: number;
  totalBookings: number;
  cancellationRate: number;
  profitMargin: number;
  avgOrderValue: number;
  repeatRatio: number;
  revenueGrowth: number;
  activeAgents: number;
  topDestination: string;
  riskScore: number;
}): string {
  const m = metrics;
  return [
    "ATLASOPS AI — EXECUTIVE SUMMARY",
    `Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
    "═══════════════════════════════════════",
    "KEY PERFORMANCE INDICATORS",
    "═══════════════════════════════════════",
    "",
    `Total Revenue:        ₹${(m.totalRevenue / 10000000).toFixed(2)} Cr`,
    `Revenue Growth:       ${m.revenueGrowth > 0 ? "+" : ""}${m.revenueGrowth}%`,
    `Profit Margin:        ${m.profitMargin}%`,
    `Average Order Value:  ₹${m.avgOrderValue.toLocaleString()}`,
    "",
    `Total Bookings:       ${m.totalBookings.toLocaleString()}`,
    `Cancellation Rate:    ${m.cancellationRate}%`,
    `Repeat Booking Ratio: ${m.repeatRatio}%`,
    "",
    `Active Agents:        ${m.activeAgents}`,
    `Top Destination:      ${m.topDestination}`,
    `Risk Score:           ${m.riskScore}/100`,
    "",
    "═══════════════════════════════════════",
    "OPERATIONAL STATUS",
    "═══════════════════════════════════════",
    "",
    m.riskScore >= 80 ? "System Status: NORMAL" :
    m.riskScore >= 60 ? "System Status: ELEVATED RISK" :
    "System Status: CRITICAL — REVIEW REQUIRED",
    "",
    m.cancellationRate > 12 ? "⚠ Cancellation rate above threshold (12%)" : "✓ Cancellation rate within normal range",
    m.profitMargin < 15 ? "⚠ Profit margin below target (15%)" : "✓ Profit margin healthy",
    m.revenueGrowth < 0 ? "⚠ Revenue declining period-over-period" : "✓ Revenue growth positive",
    "",
    "— AtlasOps AI Operations Intelligence",
  ].join("\n");
}

// --- Download Helper ---

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// --- KPI Snapshot ---

export function exportKPISnapshot(kpis: { label: string; value: string | number; change?: string }[]): void {
  const lines = [
    "AtlasOps AI — KPI Snapshot",
    `Date: ${new Date().toISOString().split("T")[0]}`,
    "",
    ...kpis.map(k => `${k.label}: ${k.value}${k.change ? ` (${k.change})` : ""}`),
    "",
    "— Generated by AtlasOps AI",
  ];
  downloadFile(lines.join("\n"), "atlasops-kpi-snapshot", "text/plain");
}
