-- ============================================================
-- AtlasOps AI — PostgreSQL Schema
-- Supabase Foundation
-- ============================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- REFERENCE TABLES
-- ============================================================

-- Destinations
CREATE TABLE IF NOT EXISTS destinations (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name          TEXT NOT NULL UNIQUE,
  country       TEXT NOT NULL,
  region        TEXT NOT NULL,
  type          TEXT NOT NULL CHECK (type IN ('domestic', 'international')),
  base_price    INTEGER NOT NULL DEFAULT 0,
  cancel_rate   NUMERIC(5,2) NOT NULL DEFAULT 0,
  popularity    INTEGER NOT NULL DEFAULT 5 CHECK (popularity BETWEEN 1 AND 10),
  seasonal_peak TEXT[] DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Agents
CREATE TABLE IF NOT EXISTS agents (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name              TEXT NOT NULL,
  email             TEXT NOT NULL UNIQUE,
  region            TEXT NOT NULL,
  skill_level       NUMERIC(3,1) NOT NULL DEFAULT 5.0 CHECK (skill_level BETWEEN 1 AND 10),
  response_time_min INTEGER NOT NULL DEFAULT 15,
  satisfaction      NUMERIC(2,1) NOT NULL DEFAULT 4.0 CHECK (satisfaction BETWEEN 1 AND 5),
  join_date         DATE NOT NULL DEFAULT CURRENT_DATE,
  active            BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Customers
CREATE TABLE IF NOT EXISTS customers (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name        TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT,
  city        TEXT,
  is_repeat   BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- FACT TABLE
-- ============================================================

-- Bookings (source of truth)
CREATE TABLE IF NOT EXISTS bookings (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  agent_id        UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  destination_id  UUID NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  package_name    TEXT NOT NULL,
  package_type    TEXT NOT NULL CHECK (package_type IN ('domestic', 'international')),
  status          TEXT NOT NULL CHECK (status IN ('confirmed', 'cancelled', 'pending', 'completed')),
  payment_status  TEXT NOT NULL CHECK (payment_status IN ('paid', 'partial', 'refunded', 'pending')),
  amount          INTEGER NOT NULL CHECK (amount > 0),
  profit          INTEGER NOT NULL DEFAULT 0,
  booking_date    DATE NOT NULL,
  travel_date     DATE NOT NULL,
  return_date     DATE NOT NULL,
  pax             INTEGER NOT NULL DEFAULT 1 CHECK (pax > 0),
  source          TEXT NOT NULL CHECK (source IN ('website', 'referral', 'agent', 'social', 'walk-in')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- ANALYTICS TABLES
-- ============================================================

-- Operational Metrics (daily rollups)
CREATE TABLE IF NOT EXISTS operational_metrics (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  date              DATE NOT NULL UNIQUE,
  total_bookings    INTEGER NOT NULL DEFAULT 0,
  total_revenue     BIGINT NOT NULL DEFAULT 0,
  total_profit      BIGINT NOT NULL DEFAULT 0,
  cancellation_count INTEGER NOT NULL DEFAULT 0,
  cancel_rate       NUMERIC(5,2) NOT NULL DEFAULT 0,
  avg_order_value   INTEGER NOT NULL DEFAULT 0,
  domestic_revenue  BIGINT NOT NULL DEFAULT 0,
  intl_revenue      BIGINT NOT NULL DEFAULT 0,
  repeat_bookings   INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Insights (generated by insight engine)
CREATE TABLE IF NOT EXISTS insights (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  severity      TEXT NOT NULL CHECK (severity IN ('critical', 'warning', 'info', 'positive')),
  category      TEXT NOT NULL CHECK (category IN ('revenue', 'operations', 'performance', 'risk', 'growth', 'anomaly')),
  title         TEXT NOT NULL,
  detail        TEXT NOT NULL,
  metric        TEXT,
  metric_value  NUMERIC,
  recommendation TEXT,
  source        TEXT NOT NULL DEFAULT 'rule-based',
  is_new        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Anomalies (detected by anomaly engine)
CREATE TABLE IF NOT EXISTS anomalies (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type            TEXT NOT NULL,
  severity        TEXT NOT NULL CHECK (severity IN ('critical', 'warning', 'info')),
  title           TEXT NOT NULL,
  detail          TEXT NOT NULL,
  observed_value  NUMERIC,
  expected_value  NUMERIC,
  deviation       NUMERIC,
  affected_entity TEXT,
  resolved        BOOLEAN NOT NULL DEFAULT false,
  detected_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_agent ON bookings(agent_id);
CREATE INDEX IF NOT EXISTS idx_bookings_destination ON bookings(destination_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_date_status ON bookings(booking_date, status);
CREATE INDEX IF NOT EXISTS idx_bookings_type ON bookings(package_type);
CREATE INDEX IF NOT EXISTS idx_bookings_source ON bookings(source);
CREATE INDEX IF NOT EXISTS idx_metrics_date ON operational_metrics(date);
CREATE INDEX IF NOT EXISTS idx_insights_severity ON insights(severity);
CREATE INDEX IF NOT EXISTS idx_insights_created ON insights(created_at);
CREATE INDEX IF NOT EXISTS idx_anomalies_severity ON anomalies(severity);
CREATE INDEX IF NOT EXISTS idx_anomalies_resolved ON anomalies(resolved);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
